const mongoose = require('mongoose');

const paymentSchema = new mongoose.Schema({
    uri:{
        type:String
    },
    tl_method:{
        type:String
    },
    params:{
        transaction_id:{
            type:String
        },
        transaction_status:{
            type:String
        },
        amount:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'Price'
        },
        currency:{
            type:mongoose.Schema.Types.ObjectId,
            ref:'Price'
        },
        additionalProperties:{
            type:String
        }
    },
    type:{
        type:String
    },
    status:{
        type:String
    },
    time:{
        type:mongoose.Schema.Types.ObjectId,
        ref:'Time' 
    },
    collected_by:{
        type:String
    },
    collection_amount:{
        type:String
    },
    settlement_window:{
        type:String
    },
    settlement_window_status:{
        type:String
    },
    settlement_details:[{
        settlement_counterparty:{
            type:String
        },
        settlement_type:{
            type:String
        },
        settlement_bank_account_no:{
            type:String
        },
        settlement_ifsc_code:{
            type:String
        },
        upi_address:{
            type:String
        },
        bank_name:{
            type:String
        },
        branch_name:{
            type:String
        },
        beneficiary_name:{
            type:String
        },
        beneficiary_address:{
            type:String
        },
        settlement_status:{
            type:String
        },
        settlement_reference:{
            type:String
        },
        settlement_timestamp:{
            type:String
        }
    }]
},{
    timestamps:true
});

module.exports = mongoose.model('Payment',paymentSchema);